//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotelrooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotelrooms()
        {
            this.listresidents = new HashSet<listresidents>();
        }
    
        public string number_room { get; set; }
        public string places { get; set; }
        public string rooms { get; set; }
        public int id_class { get; set; }
        public int id_bathroom { get; set; }
        public string Equipment { get; set; }
        public string Count { get; set; }
        public int id_room { get; set; }
    
        public virtual bathroom_pick bathroom_pick { get; set; }
        public virtual hotelroom_classes hotelroom_classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listresidents> listresidents { get; set; }
    }
}
